name: master

on:
  push:
    branches:
      - master
jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build from sources
      run: ./gradlew build
    - name: Send coverage report
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
    - uses: actions/upload-artifact@v1
      with:
        name: app
        path: build/app/email-api-1.0.0-SNAPSHOT.jar
  build-docker:
    runs-on: ubuntu-latest
    needs: build-gradle
    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@v1
      with:
        name: app
        path: build/app/
    - name: Setup git ssh access for tag management
      uses: webfactory/ssh-agent@v0.1.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Setup git latest tag for image publishing purposes
      run: git switch -c ${GITHUB_REF##*/}
        && echo $(ls -la ./)
        && origin_url="git@github.com:jvmops/email-api.git"
        && git remote set-url origin "$origin_url"
        && echo "git-bot > origin_url set to $origin_url"
        && git tag -d latest || true
        && git push --delete origin latest || true
        && git tag latest
        && echo "git-bot > branch re-tagged"
        && git push origin latest
        && echo "git-bot > latest tag pushed to origin"
    - name: Publish docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jvmops/email-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true

